---
# Play nginx installation
- name: Install lighthouse
  hosts: lighthouse
  roles:
  - lighthouse

# Play clickhouse installation
- name: Install clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

# Play vector installation
- name: Install vector
  hosts: vector
  roles:
    - vector
