filebeat.inputs:
  - type: container
    paths: 
      - '/var/lib/docker/containers/*/*.log'
    scan_frequency: 30s

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.logstash:
  hosts: ["192.168.32.5:5044"]
  # indices:
  #  - index: "filebeat-%{[@metadata][target_index]}-%{+YYYY.MM.dd}"

logging.json: true
logging.metrics.enabled: false