---
# a version of clickhouse we need
clickhouse_version: "22.3.3.44"

# packages we need for clickhouse installation
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static

# specify clickhouse ports
clickhouse_http_port: 8123
clickhouse_tcp_port: 9000
clickhouse_interserver_http: 9009

clickhouse_listen_host:
  - "192.168.150.0/24"

clickhouse_path_configdir: "/etc/clickhouse-server"
clickhouse_path_user_files: "{{ clickhouse_path_configdir }}/users.d"
clickhouse_path_data: "/var/lib/clickhouse"
clickhouse_path_tmp: "{{ clickhouse_path_base }}/tmp/"
clickhouse_path_logdir: "/var/log/clickhouse-server"
clickhouse_service: 'clickhouse-server.service'

# specify networks from which users can connect to the Clickhouse
clickhouse_networks_default:
  - "::1"
  - "127.0.0.1"

clickhouse_networks_custom:
  - "::/0"

# set users for the Clickhouse configuration
clickhouse_users_default:
  - { name: "default", password: "", networks: "{{ clickhouse_networks_default }}", profile: "default", quota: "default", access_management: "1", comment: "Default user for login if user not defined" }

clickhouse_users_custom:
  - { name: "readonly", password: "", networks: "{{ clickhouse_networks_default }}", profile: "readonly", quota: "default", comment: "Example of user with readonly access" }

clickhouse_profiles_default:
 default:
   max_memory_usage: 1000000000
   use_uncompressed_cache: 0
   load_balancing: random
   max_partitions_per_insert_block: 100
 readonly:
   readonly: 0

clickhouse_profiles_custom:
  default:
    max_memory_usage: 1000000000
    use_uncompressed_cache: 0
    load_balancing: random
    max_partitions_per_insert_block: 100
  readonly:
    readonly: 0

clickhouse_quotas_intervals_default:
  - { duration: 3600, queries: 0, errors: 0, result_rows: 0, read_rows: 0, execution_time: 0 }

clickhouse_quotas_default:
  - { name: "default", intervals: "{{ clickhouse_quotas_intervals_default }}", comment: "Default quota - count only" }

clickhouse_quotas_custom:
  - { name: "vector", intervals: "{{ clickhouse_quotas_intervals_default }}", comment: "vector quota without limiting usage" }